services:
  backend:
    build: ./api
    container_name: fizzbuzz-backend
    ports:
      - "5271:5271"
    environment:
      - DB_HOST=db
      - DB_PORT=1433
      - DB_NAME=mydb
      - DB_USER=sa
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      - db

  frontend:
    build: ./next
    container_name: fizzbuzz-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
    - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
    - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    - AWS_REGION=${AWS_REGION}

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: fizzbuzz-db
    environment:
      SA_PASSWORD: ${DB_PASSWORD}
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - db-data:/var/opt/mssql

volumes:
  db-data: